/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefineryRouteImport } from './routes/refinery'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as CoreRouteImport } from './routes/core'
import { Route as IndexRouteImport } from './routes/index'

const RefineryRoute = RefineryRouteImport.update({
  id: '/refinery',
  path: '/refinery',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core': typeof CoreRoute
  '/refinery': typeof RefineryRoute
  '/observatory': typeof ObservatoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/core' | '/refinery' | '/observatory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/core' | '/refinery' | '/observatory'
  id: '__root__' | '/' | '/core' | '/refinery' | '/observatory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreRoute: typeof CoreRoute
  RefineryRoute: typeof RefineryRoute
  ObservatoryRoute: typeof ObservatoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refinery': {
      id: '/refinery'
      path: '/refinery'
      fullPath: '/refinery'
      preLoaderRoute: typeof RefineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreRoute: CoreRoute,
  RefineryRoute: RefineryRoute,
  ObservatoryRoute: ObservatoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
